### PR TITLE
Add rules_shell loads where needed

### LINKED ISSUE #397: Missing sh_binary loads for Bazel 9 support
While preparing rules_python for Bazel 9, which removes the builtin sh rules (among others), I came across an un-loaded sh_binary usage:

https://github.com/bazel-contrib/rules_bazel_integration_test/blob/main/bazel_integration_test/private/bazel_binaries.bzl#L124

This just needs to have `load("@rules_shell//shell:sh_binary.bzl", "sh_binary")` added

### PR DESCRIPTION
**Pull request by ted-xie**
Unblocks https://github.com/bazelbuild/rules_android/issues/278.

Closes #397.

### CODE REVIEW

**Review by cgrindel — APPROVED** [review]

**Comment by ted-xie** [comment]
@cgrindel Thanks for approving this so quickly! If it's not too much trouble, would you mind also creating a new release that includes this commit?

**Comment by cgrindel** [comment]
Working on it. I need #402 to merge before I can create a release.

**Comment by cgrindel** [comment]
[Release 0.27.0](https://github.com/bazel-contrib/rules_bazel_integration_test/releases/tag/v0.27.0)  is out. If you use bzlmod, you will need to wait until [the BCR PR](https://github.com/bazelbuild/bazel-central-registry/pull/3266) merges.

**Comment by aignas** [comment]
I think `sh_library` load is also needed in https://github.com/bazel-contrib/rules_bazel_integration_test/blob/d3e578ba9be36f57e0a52a9878c4b12ab45b0a42/tools/BUILD.bazel#L14

**Pull request merged**
