### PR TITLE
Add startup options to bazel binary template

### PR DESCRIPTION
**Pull request by LeFrosch**
Hi, as described in #349 I would like to add pass `--nosystem_rc` as a startup option to bazel. 

This PR introduces the `BIT_STARTUP_OPTIONS` environment variable in the bazel binary template that can be used to pass arbitrary flags to bazel. Also I added `startup_options` filed to the test macros for convenance.

### CODE REVIEW

**Comment by cgrindel** [comment]
FYI. I added a comment to #349.

**Comment by cgrindel** [comment]
@LeFrosch Can you run `bazel run //:tidy` and commit the changes?

**Review by cgrindel — APPROVED** [review]

**Review by cgrindel — CHANGES_REQUESTED** [review]
It looks like there are some test failures that need to be addressed. I will remove my approval for now. Let me know when you have chased these down.

**Comment by LeFrosch** [comment]
I thanks for considering this PR. As far as I can tell the test should now pass.

**Pull request merged**
