### PR TITLE
Update versions in MODULE.bazel to match deps.bzl.

### PR DESCRIPTION
**Pull request by katre**
Update after #244 .

### CODE REVIEW

**Comment by cgrindel** [comment]
Was there an error that encouraged the deps update for the root module? If not, we want to maintain the lowest version of the root module deps. This prevents clients of the ruleset from being "upgraded" unnecessarily.

**Comment by katre** [comment]
Should I not have accepted #244, then? We can revert it. We should make the versions match, however.

I'll update this to do that later today.

**Comment by cgrindel** [comment]
Confusingly, the legacy WORKSPACE is not an issue. A client can override versions declared by their transitive dependencies. The Renovate bot is configured to do the following:

1. Upgrade all legacy WORKSPACE declarations that it finds.
2. Upgrade the bzlmod dependencies in any `MODULE.bazel` that is not at the root.

So, the Renovate PRs are safe to approve.

**Comment by katre** [comment]
Thanks for clarifying. Should I close this PR, then?

**Comment by cgrindel** [comment]
Yes. Thanks.

**Pull request closed without merging**
